menu:
- {name: 'Home', url: '/'}
- {name: 'About', url: '/about.html'}
- {name: 'Languages', url: '/languages'}
# - {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
# - {name: 'cv', url: '/cv'}
# - {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

languages:
- {name: 'Gilaki', url: 'gilaki'}
- {name: 'Southern Kurdish', url: 'southern-kurdish'}
- {name: 'Gorani', url: 'gorani'}
- {name: 'Laki', url: 'laki'}
- {name: 'Luri', url: 'luri'}
- {name: 'Mazanderani', url: 'mazanderani'}
- {name: 'Talysh', url: 'talysh'}
- {name: 'Zazaki', url: 'zazaki'}

social:
- {icon: 'github', link: 'https://github.com/DOLMA-NLP'}
- {icon: 'twitter', link: 'https://x.com/sina_ahm'}
- {icon: 'telegram', link: 'https://t.me/+qibLbXbnp-05NWQ0'}
- {icon: 'envelope', link: 'mailto:sinaahmadi.yae@gmail.com'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
